INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(1, '상체운동1', '상체운동1', 'C3TqpGgnIoI', 'G001');    
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(2, '상체운동2', '상체운동2', '54tTYO-vU2E', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(3, '상체운동3', '상체운동3', 'aoH7qNedO8k', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(4, '하체운동1', '하체운동1', 'NDsjmxTROEo', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(5, '하체운동2', '하체운동2', 'EDq180TqRIc', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(6, '하체운동3', '하체운동3', '9WhpAVOSyl8', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(7, '복근운동1', '복근운동1', 'PjGcOP-TQPE', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(8, '복근운동2', '복근운동2', '2Uv1B3kjCOI', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(9, '허리운동1', '허리운동1', '1uJV1ZmzeoI', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(10, '허리운동2', '허리운동2', 'YRh9yuznweg', 'G001');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(11, '상체_가슴운동1', '상체_가슴운동1', 'c_5ENJWekbQ', 'G002');    
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(12, '상체_가슴운동2', '상체_가슴운동2', 'icIwg6zpQys', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(13, '상체_어깨운동1', '상체_어깨운동1', 'fr-5MKeRfVU', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(14, '상체_어깨운동2', '상체_어깨운동2', '5tjgmucZke8', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(15, '상체_팔운동1', '상체_팔운동1', 'NqSfpsJn8M8', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(16, '하체_다리운동1', '하체_다리운동1', 'tzN6ypk6Sps', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(17, '하체_다리운동2', '하체_다리운동2', 'xpzMr3nSOIE', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(18, '하체_허벅지운동1', '하체_허벅지운동1', '8UNMmdc0Lzw', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(19, '하체_허벅지운동2', '하체_허벅지운동2', 'tOJyThLjVbI', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(20, '몸_복근운동1', '몸_복근운동1', 's2pkdUiCRTM', 'G002');
INSERT INTO PTVIDEO(VIDEO_NUM,VIDEO_NAME,VIDEO_CONTENT,VIDEO_PATH,GRADE_CODE)
VALUES(21, '몸_허리운동1', '몸_허리운동1', 'TiMJOt6stPE', 'G002');

INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (1,'어깨운동','어깨운동의 종류는 숄더 프레스(바벨, 덤벨), 비하인드 넥 프레스, 프론트 레이즈, 사이드 레터럴 레이즈, 벤트 오버 레터럴 레이즈, 업라이트 로우, 아놀드 프레스, 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (2,'팔운동','팔운동의 종류는 이두, 삼두, 전완운동으로 크게 나뉘며 이두운동은 원암 케이블 컬, 케이블 컬, 시티드 컨센트레이션 덤벨 컬, 투암 시티드 프리처 덤벨 컬, 시티드 프리처 덤벨 컬, 프리처 벤치 이지바 컬, 시티드 어러네이트 덤벨 컬 등이 있고, 삼두운동은 덤벨 투암 오버헤드 트라이셉스 익스테션, 인클라인 바벨 트라이셉스 인스텐션, 시티드 바벨 트라이셉스 인스텐션, 스텐딩 바벨 트라이셉스 인스텐션 등이 있고, 전완근운동은 시티드 바벨 팜스 다운 리스트 컬, 스탠딩 롤러 리스트 컬, 벤치 팜스 업 리스트 컬, 스탠딩 비하인드 바벨 리스트 컬, 원암 덤벨 리스트 컬 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (3,'가슴운동','가슴운동의 종류는 상부, 중부, 하부로 크게 나뉘며 중부운동은 일반적인 바벨, 덤벨을 이용한 벤치프레스, 팔굽혀펴기 등이 있고, 상부운동은 인클라인 벤치프레스, 인클라인 덤벨 플랑이, 발을 높이 올려 놓고하는 팔굽혀펴기 등이 있고, 하부운동은 딥스, 디클라인 벤치프레스, 인클라인 푸시업 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (4,'허벅지운동','집에서 할 수 있는 허벅지운동의 종류는 대표적으로 스쿼트, 내전근운동, 브릿지, 사이드 레그 리프트, 데드리프트 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (5,'다리운동','집에서 할 수 있는 다리운동의 종류는 대표적으로 스쿼트, 런지, 측면운동, 스텝박스, 사두근 수축 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (6,'발목운동','발목운동의 종류는 수건을 이용하여 장딴지 늘리기, 서서 장딴지근 늘리기, 발등 굽힘운동, 수동적 관절 가동 범위 운동, 탄력밴드 걸고 번짐운동, 탄력밴드 걸고 발바닥 굽힘 운동 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (7,'복근운동','복근운동의 종류는 할로우, 트위스트, 시저스킥, 리버스 크런치, 싯업 등이 있습니다.');
INSERT INTO EXERCISE(EXE_NUM,EXE_NAME,EX_CONTENT)
VALUES (8,'허리운동','허리운동의 종류는 허리 회전운동, 햄스트링 스트레칭, 이상근 스트레칭, 장요근 스트레칭, 골반 경사 회전, 코브라 스트레칭, 브릿지, 슈퍼맨 운동, 버드 독, 플랭크 등이 있습니다.');

INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(1,'삶은 계란흰자입니다.','삶은 계란흰자',17,0.06,3.58,0.24,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(2,'단백질 쉐이크 초코맛입니다.','단백질 쉐이크 초코맛',90,0,11,12,2);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(3,'현미밥입니다.','현미밥',320,2.2,6,69,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(4,'닭가슴살야채볶음입니다.','닭가슴살야채볶음',82,1.6,13,3,2);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(5,'아몬드 23알입니다.','아몬드 23알',173.7,1.14,6.345,6.465,1.305);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(6,'사과입니다.','사과',61,0.17,0.35,16.33,5);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(7,'고구마입니다.','고구마',193,0.22,2.6,45.85,5);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(8,'된장찌개입니다.','된장찌개',115,5,4,13,8);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(9,'고등어입니다.','고등어',12.6,0.69,1.59,0,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(10,'두부입니다.','두부',99,5.26,10.12,3.51,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(11,'샐러드입니다.','샐러드',102,6.29,2.29,10.04,4.19);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(12,'시리얼입니다.','시리얼',405,3.3,11,83,7);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(13,'현미밥입니다.','현미밥',320,6,2.2,69,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(14,'고구마순나물입니다.','고구마순나물',50.18,3.99,1.59,2.13,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(15,'브로콜리입니다.','브로콜리',34,0.37,2.82,6.64,0);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(16,'방울토마토 1개 입니다.','방울토마토 1개',3,0.03,0.15,0.67,3);
INSERT INTO FOOD(FOOD_NUM,FOOD_CONTENT,FOOD_NAME,FOOD_KCAL,FOOD_FAT,FOOD_PROTEIN,FOOD_RICE,FOOD_SWEET)
VALUES(17,'삶은 계란입니다.','삶은 계란',77,5.28,6.26,0.56,0);























